### ISSUE TITLE
Berry curvature on a sphere

### ISSUE THREAD

**Issue by neelravi** [quanshengwu/wannier_tools#10]
Dear QuanSheng Wu,
  The current implementation gives 2D map of berry curvature on a plane. I was thinking of doing it on a sphere (enclosing the Weyl node). Do you have plans to implement this, or should I go ahead and do this? I may have to change the kslice from Cartesian to a spherical polar system and map the values on the surface of that sphere with the color palette. 

Regards,

Ravindra.

**Comment by quanshengwu** [comment]
Dear Ravindra, 

Thanks for your suggestion, I will implement it in the next release. 

Best regards, 

QuanSheng
