### ISSUE TITLE
How about 2d version?

### ISSUE THREAD

**Issue by suan12** [quanshengwu/wannier_tools#11]
Dear QuanSheng Wu,
      Does the current implementation add 2D version for novel two-dimensional topological materials? I was thinking of doing it. Do you have plans to add this? If possible, it is better to attach an example (such as graphene)?.
Best wishes,
suan12.

**Comment by quanshengwu** [comment]
Dear suan12, 
Thanks for your question. 

Can I ask if you want to study 2D materials or study 2D model?
If you want to study 2D materials, you can just follow the 3D version. The  different thing is that you only need to analyze kz=0 or kz=0.5 plane, other planes are trivial. 

If you want to study 2D model,  at present, the version we have can calculate some properties. We only need to modify the 3D version.  Actually this part is almost finished. Please be patience. 

Best, 
QuanSheng

**Comment by suan12** [comment]
Thank you for your answer! Looking forward to your new version.
