### ISSUE TITLE
Could the wanntools directly compute the chern number?

### ISSUE THREAD

**Issue by tron1989** [quanshengwu/wannier_tools#12]
Dear Quansheng,

Could the wanntools directly compute the chern number of a possible QAH insulator?

For there are many subroutines in wanniercenter.f90 and wanniercenter_adaptive.f90, and I am not quite sure if there is a subroutine could directly compute the Chern number of a 2D materials.

Thanks

**Comment by quanshengwu** [comment]
Dear tron1989, 

Yes,  you can directly calculate Chern number by using Chern_3D_calc tags. For 2D materials, you only need to study kz=0 plane. 

Actually, you also can use wanniercenter_calc tag to calculate Chern number. Please set KPLANE_BULK like this
0.0 0.0 0.0
1.0 0.0 0.0
0.0 1.0 0.0

Best, 
QuanSheng

**Comment by tron1989** [comment]
Thanks a lot,

In fact, a few days ago I have tested what you said, but the result is weird. The actual Chern number should be 3, but the  wanniercenter_calc gives zero, and the Chern_3D_calc in the k3=0 plane is 1.

**Comment by quanshengwu** [comment]
Thanks for the reports. 
Could you send me the input file and the tight binding model to me?

**Comment by tron1989** [comment]
Ok, I will send it to you as soon as possible.

**Comment by tron1989** [comment]
Dear Quansheng，

I have sent it to your gmail.

Please take care of it.

Thanks

**Comment by quanshengwu** [comment]
I got your input data and run it. 

Your setting for wanniercenter_calc are correct and the wilson loop calculation is correct too. 

Please change the last plotting line in wcc.gnu from 
```
plot 'wcc.dat' u 1:2 w l lw 2  lc 'blue', \
 for [i=4:    12] 'wcc.dat' u 1:i w p  pt 7  ps 1.1 lc 'red'
```
to
```
plot 'wcc.dat' u 1:3 w p ps 1 lc 'blue'
```

Then you can count the winding number (Chern number) from the plot.

**Comment by tron1989** [comment]
Thanks a lot！

On the other hand, if I want to get knowledge of the output files, one way is to read your source code directly. Is it possible to give some simple explanation about the output files in the DOC or on the head of the output files?

**Comment by quanshengwu** [comment]
Actually, I write some explanations of output data in the documentation. Yet not all of them. 
Thanks for your suggestion, I will write more  explanations.
