### ISSUE TITLE
Band structure of a slab using wannier-tools

### ISSUE THREAD

**Issue by khamaribramha** [quanshengwu/wannier_tools#13]
I am using wannier_tools to get the band structure of a slab. I would like to get the slab band structure with both top and bottom surface being the same layer. For example, If I want to study 001 surface  of cubic ABO3,  How to set both bottom and top layer as AO in the input file(wt.in) of wannier_tools.

**Comment by quanshengwu** [comment]
I am sorry that the top and bottom surface are fixed to the unit cell you specified in the input file wt.in. If you want to study different atomic surface, you have to shift your POSCAR and generate new Wannier functions again. I am trying to improve this problem recently.

**Comment by khamaribramha** [comment]
Thank you for your quick reply. The compound for which I am trying to obtain slab band structure using wannier_tools is KBiO3. I choose all the atoms K, Bi and O for projectors and projects them to wannier basis and select Nslab = 10(default value in wt.in) for slab calculation. Then what will be the top and bottom layer?. If an odd number is choosen for Nslab, what will be the top and bottom layer.

**Comment by quanshengwu** [comment]
It also depends on the position of your unit cell. 
If you studied the (001) surface, then the left surface is the z=c surface and right surface is the z=0 surface. The top and bottom surface don't depend on the "Nslab", because Nslab is the number of the unit cell.

**Comment by khamaribramha** [comment]
The atomic positions in the unit cell of KBiO3 are (0 0 0), (0.5 0.5 0.5)
and (0.5 0.5 0) for K, Bi and O respectively. Therefore Z=0 surface has KO
layer whereas Z=c surface has BiO2 layer. Am I correct?.

**Comment by quanshengwu** [comment]
Yes, you are correct, I think so.

**Comment by khamaribramha** [comment]
Inorder to construct 001 surface one need to break the periodicity along z
direction. In the input file (wt.in) for slab calculation, we are just
selecting the two directions along which periodicity is maintained and also
choosing the third direction along which periodicity is broken. Could you
explain how the breaking of periodicity has been taken care.



‌

**Comment by quanshengwu** [comment]
@khamaribramha  The third direction is just for coding convenience. Now, you could use MILLER_INDICES instead of SURFACE CARD. Please check with this link
http://www.wanniertools.com/input.html#surface

**Comment by nfh** [comment]
Dear QuanSheng, 

I have a query about the choice of unit cell when using miller_indices. I'll use output to underpin my question.

Let's assume I have a simple bcc unit cell with real space vectors:

 ```
We found LATTICE card
>> lattice information (Angstrom)
    1.577503    1.577503    1.577503
   -1.577503    1.577503    1.577503
   -1.577503   -1.577503    1.577503
```

Then I choose a 100 surface by noting in the input card

```
MILLER_INDICES 
1 0 0
```

and it gives

 ```
 We found MILLER_INDEX card for slab calculations
  Miller indices are :     1     0     0
   Congratulations, you got a unit cell that has 
  the same volume as the original unit cell 
  The unitary rotation matrix is : 
     0.000    -1.000     0.000
     0.000     0.000    -1.000
     1.000     0.000     0.000
  
 The lattice vectors for new cell are : 
 R1=     1.578    -1.578    -1.578
 R2=     1.578     1.578    -1.578
 R3=     1.578     1.578     1.578
  Where R1 and R2 are in (hkl) plane
 Cell_Volume:    7.03858620402572     
 Ra2, Rb2
    2.7323    0.0000
    0.9108    2.5761
 Ka2, Kb2
    2.2996   -0.8130
    0.0000    2.4391
```

Exactly the last given surface real space vectors make wonder. Taking the 100 surface of a bcc unit cell should conveniently give me lattice vectors with 90°. Why ist this not the case here? Furthermore, are the given Ka2, Kb2 exactly the vectors to span the 100-surface BZ, i.e. where the surface high symmetry points in KPATH_SLAB have to be related to?

maybe you can point me to a possible error I did,

all the best and thank you,

**Comment by quanshengwu** [comment]
Hi @nfh ,

I am sorry to tell you that the Miller indices in WannierTools depend on the lattice vectors you specified in the Lattice card. Those Miller indices are not the ones that depend on the conventional cell. 

If this illustration is confused with you, please use the SURFACE CARD instead.

**Comment by myhanna** [comment]
I am using wannier_tools to calculate the slab band. But, which I need is how to generate POSCAR-slab output? Are there any parameters that I add to input wt.in?

**Comment by phyzhj** [comment]
> I am using wannier_tools to calculate the slab band. But, which I need is how to generate POSCAR-slab output? Are there any parameters that I add to input wt.in?

I have the same question. While I calculated Surface state using WannierTools2.5.1 with SlabSS_calc=T, no POSCAR-slab output appeared. Are there any parameters I need to add to wt.in?
