### ISSUE TITLE
Bug in WannierTools v2.7.0, please fix in future updates

### ISSUE THREAD

**Issue by Rahullmp** [quanshengwu/wannier_tools#139]
There is a bug in BulkBand_points_calc routine. 

1. If you specify your KPOINTS_3D k-points in "Cartisen" coordinates, then the energy eigenvalues are incorrect. I think this is due to the incorrect conversion of cartesian to direct coordinates in internal routines. This can be easily verified, once you do the calculation you can check the O/P file "bulkek-pointsmode.dat" where the cartesian and direct coordinates are mismatched.

2. However if you use Direct coordinates in KPOINTS_3D, this will give you the correct result.

I would suggest other users use Direct coordinates while using this subroutine and request developers to fix this in future updates. It took me a full day to track the issue. I hope this will help others.

**Comment by Rahullmp** [comment]
Dear developers, @quanshengwu 

This is the second bug I am reporting in WannierTools v270, please check.

While using the WeylChirality_calc module, when I specify the WEYL_CHIRALITY points in the input file, the conversion of coordinates is incorrect in the O/P.

In the input file, if I write weyl points in cartesian coordinates, then in the output file its Direct coordinates are wrong and vice-versa. Please check and confirm this bug from your side and fix this in future updates.

Thanks and regards, 
Rahul Verma

**Comment by quanshengwu** [comment]
Dear Rahul, 

Thank you very much for pointing out these two bugs. It's fixed now by multiplying Angstrom2atomic to the cartesian coordinates. 

Best, 
Quansheng Wu

**Comment by Rahullmp** [comment]
Dear  @quanshengwu,

Thank you !
