### ISSUE TITLE
Edge states

### ISSUE THREAD

**Issue by sfragkos** [quanshengwu/wannier_tools#14]
Hello sir
If i want to study the edge states of a material, for example 1T' MoTe2, should i take it's bulk or monolayer?
If i take the monolayer, how am i supposed to see the side surface since my KPOINTS file is an 21x21x1 grip? Is it possible?

**Comment by sfragkos** [comment]
I'm talking about 1T' MoTe2 because they say that the 1 monolayer is topological insulator.

**Comment by quanshengwu** [comment]
For a 2D material, you could think it as a 3D material like what you treat it in the DFT simulations. 
But if you are interested in the edge states of a 2D material, you should look at the side surface like (010) 0r (100).

**Comment by sfragkos** [comment]
Thanks for your answer
But, whats the right way? Should i treat it normally like a 2D or like a 3D.

**Comment by quanshengwu** [comment]
You can think like this. There is no 2D material in VASP simulation. You always treat it as a 3D material with weak coupling along the z direction. You can treat it the same way when you use WannierTools.

**Comment by RAGRAGUI** [comment]
hello, I wish to work 2D materials with quantum espresso and wannierTools, than what I can edit in the examples that makes by VASP ?.
  because quantum espresso processes 2D materials directly.
