### ISSUE TITLE
surface state ARPES calculation and  Fermi arc calculation

### ISSUE THREAD

**Issue by caicaicai123** [quanshengwu/wannier_tools#15]
Hello sir
 There are two types of output  files  _r and _l  after  surface state ARPES  and Fermi arc calculation,  what  do these two files mean and what's the difference between them ?  If I want to get the surface state or fermi arc plot ,which files should  I  choose?

**Comment by quanshengwu** [comment]
Please check with this link.
http://www.wanniertools.com/features.html#sscalculation

**Comment by caicaicai123** [comment]
Dear Mr Wu,
Thank you for your reply. There  is a cubic lattice that A atom located in the center unit cell, where B atom located in the corner of the unit cell. If I calculate the 001 surface states, then the surfdos_l is corresponded to the surface that A atom termination or B atom termination?

**Comment by quanshengwu** [comment]
@caicaicai123  Basically, yes.
