### ISSUE TITLE
Confusion about 2d material

### ISSUE THREAD

**Issue by hashmi1234** [quanshengwu/wannier_tools#18]
Dear @quanshengwu , 
You have developed a great code. You have shown all examples for 3D systems. I wanted to calculate the Berry curvature, edge states, Z2, spin texture for 2d material, like MoS2 or graphene. Should i use 2d version of wannier_tools or 3d version of wannier_tools.?
Can you give any example or just check this input file.

**Comment by quanshengwu** [comment]
Dear @hashmi1234 , 

I updated a example of MoS2. Please check the new version and the documentation.
http://www.wanniertools.com/tutorials/MoS2-1Tp.html

You don't have to use the 2D version which is not well tested. Please just use the 3D version of WannierTools.
