### ISSUE TITLE
Spin texture of rashba/ Dresselhau splitting. 

### ISSUE THREAD

**Issue by nilcm90** [quanshengwu/wannier_tools#19]
Dear Sir, 

Wannier_tool is really a helpful code for topological study.  Spin texture of surface of a topological insulator and Rashba bands splitting ( more precisely, Dresselhaus effect for a non centro-symmetric material ) is locally quite similar. Is it possible to study the spin texture of a bulk band ( Dresselhaus spin texture) using wannier_tool ? 

Thanks

**Comment by quanshengwu** [comment]
Dear @nilcm90 ,

I am sorry to tell you that this is not implemented yet. I would like to inform you if it is implemented in the future.

**Comment by Chengcheng-Xiao** [comment]
@nilcm90,

If you are studying a 2D material (i.e. periodical in **_a_** and **_b_**  axis , separated by an vacuum in **_c_**  axis in DFT calculation), maybe you can specify **MILLER_INDICES** to **0 0 1** (corresponding to cutting a surface at **_c_**  axis, which, is non periodical in the first place) in **SlabSpintexture_calc** calculation. 

Also, if you are using VASP as DFT calculator, spintexture plot should be easily achieved by [pyprocar](https://sourceforge.net/projects/pyprocar/) and  [vaspkit](http://vaspkit.sourceforge.net/) project at sourceforge. :)

**Comment by quanshengwu** [comment]
@nilcm90 There is a subroutine called ek_bulk_spin in ek_bulk.f90, you can modify it at your convenience.
