### ISSUE TITLE
error with pngcairo

### ISSUE THREAD

**Issue by quanshengwu** [quanshengwu/wannier_tools#2]
When you use gnuplot to generate the band structure or surface state like "gnuplot slabek.gnu", or "gnuplot arc_l.gnu", sometimes you will encounter some errors related to pngcairo. If you use Mac, please install gnuplot like this

```brew install gnuplot --with-cairo```

This means that you install gnuplot with the term cairo. please see more information related to gnuplot and cairo. 

Thanks the information from Qiu-Nan Xu

**Comment by xqn** [comment]
if your gnuplot show "Terminal type set to 'unknown' " and you can't find terminal x11, please reinstall gnuplot like this

```brew install gnuplot --with-cairo --with-x11```

Then, your terminal will be x11 and you can show pictures directly.

**Comment by quanshengwu** [comment]
Another solution, replace the "pngcairo" to "png" in the .gnu script.
