### ISSUE TITLE
Weyl Points / Nodes

### ISSUE THREAD

**Issue by sfragkos** [quanshengwu/wannier_tools#20]
Hello sir,
When I do "Find Nodes calculation" for Td-MoTe2 I find ~300 Weyl Points.
Do you know why?

**Comment by quanshengwu** [comment]
@sfragkos  Could you check the gap of the nodes?  If the gap of all the nodes are 0.000000000, then there are several reasons.
1. The "NumOccupied" number was not properly set. 
2. The WFs based TB model is not good. They can't reproduce the DFT bands.
3. There are nodal lines. For different lattice constants, softwares, psedopotentials and functionals, the electronic structure would be different.

**Comment by sfragkos** [comment]
Lots of then have gap 0.000000  but not all.
I compared the bulk band structure with the one from DFT and they look the same.
How do I choose the correct NumOccupied?

**Comment by quanshengwu** [comment]
@sfragkos 

NumOccupied : integer, Number of occupied Wannier bands. No default value.
Important: please set NumOccpuied correctly. It represents the “occpuied” wannier bands, not the total number of electrons. In the calculation of Wilson loop, the Wilson loop is the trace of NumOccupied bands. If you want to study the topology between the 8th and the 9th band, then set NumOccupied=8.

When you search Weyl points, nodal line or study the gap in some k slices, NumOccupied is also a very important. WannierTools will look for touching point or calculate the energy gap between the NumOccupied’th band and the (NumOccupied+1)’th band.

The "band" here means the energy bands calculated with the wannier tight binding model, e.g wannier90_hr.dat.

**Comment by sfragkos** [comment]
Thank you for your answer
An other question. Should these Weyl Points be symmetric to ky=0 axis?
![gapplane](https://user-images.githubusercontent.com/28385518/34714093-f83de34a-f530-11e7-862a-df0860d8e164.png)

**Comment by quanshengwu** [comment]
Yes, the positions of Weyl points should be symmetry according to mirror_xz and mirror_yz plane in MoTe2 (Space Group: Pmn2_1). So you have to improve the quality of the Wannier functions such that the positions are symmetrical.

**Comment by sfragkos** [comment]
Hello again,
Sorry if disturb you but I would like to ask you a question, which is more about physics and not about your software, and thats because i think you are one of the most capable to answer my question.
I made a Td-MoTe2 structure which has 8 Weyl Points. How can i understand if it's really a Type II Weyl semimetal (if its trivial or non-trivial)?  I'm a little bit confused on this matter.
Thanks for your help, this software really helpfull and easy to use.

**Comment by quanshengwu** [comment]
@sfragkos 

For a Weyl point, you can calculate the chirality to check whether it is a real touching point. If the chirality is non-trivial (zero), then it is a touch point. Sometimes, you have to calculate the Weyl chirality, since the minimal gap is not exactly zero due to the numerical error. In WannierTools, if you set FindNodes_calc=T, you can definitely find the absolute zero-gap touch points if there are.

For the type-II property, you have to calculate the velocity according to the definition of type-II. 

Thanks for choosing WannierTools. There are some minor updating recently, please download the latest version for your convenience.

**Comment by sfragkos** [comment]
Well, i found 8 absolute zero-gap touch points, but i don't understand the "If the chirality is non-trivial (zero), then it is a touch point", since every points has +1 or -1.
Except if you mean that the total Chern number for a pair must be zero.

**Comment by quanshengwu** [comment]
@sfragkos  Sometimes, if you use DFT package, it is hard to find the absolute zero-gap k point. For such situation, you need the chirality checks. If you found the absolute zero-gap touch points, you don't have to check with chirality calculations.

**Comment by sfragkos** [comment]
Thank you very much. One last question.
The fermi arc that connects two weyl points of opposite chirality is part of the surface state? Or its something independent?

**Comment by quanshengwu** [comment]
@sfragkos  Fermi arc is an abbreviation of the surface states in the Weyl semimetal.

**Comment by sfragkos** [comment]
Hello again Mr. Wu
Let's say that my material has 8 weyl points. At the top surface a weyl point is connected by an arc with it's symmetric along GX line.
But on the left surface, the same weyl point it's now connected by an arc with its neighboring, and not with its symmetric.
Is this normal? Can you explain me with simple words why this is happening ?
The two surfaces are terminated by different atoms. Can something like that happend in the case of MoTe2 which both surfaces are terminated by Te atoms?
Thanks for everything!

**Comment by quanshengwu** [comment]
@sfragkos That's fine. The connectivity between Weyl points depends on the potential of the surface. The Fermi arc only connects two Weyls with different chiralities. 

You could find more information in Tomas Bezdusek's paper whos is one of my friends.

Weyl semimetal from spontaneous inversion symmetry breaking in pyrochlore oxides
https://arxiv.org/pdf/1501.03029.pdf
https://journals.aps.org/prb/abstract/10.1103/PhysRevB.91.165105

Although both surfaces of MoTe2 are terminated with Te atoms, there are still two different surfaces, but only slight.

**Comment by sfragkos** [comment]
Thank you very much!
But could a Weyl Point be connected with both its neighboring and its symmetric on the same surface, and not connected with any one on the other surface?
I'm asking you because i'm trying to identify the pairs, and I'm troubled by it because almost no one talks about this in their papers.
Sorry if im being annoying

**Comment by quanshengwu** [comment]
@sfragkos  you don't have to identify the pairs. The connectivity could be any possible ones as long as the arc connects two Weyls with opposite chirality.

**Comment by Ashley-bit660** [comment]
I am facing the same issue, I am working with CoGe, wannier band structure matches well with DFT calculations, I cross-check the band that I need for Weyl point. still, I am getting more than 200 Weyl points.
Here I have two questions
1) how much does the choice of EF matter, what if I change it for two bands, or I don't use this parameter?
2) Why the positive WP are greater than NWPs.

It would be so nice of you to guide me little on this.. so that i can move forward.
Thanks

**Comment by saurabhkumarsen** [comment]
Hellow , sir
I am encountering an issue with Weyl chirality analysis. It is evident that there are Fermi arcs connecting two crossing points. However, upon calculating the Weyl chirality, I noticed that there are more instances of -1 chirality present in the WT.out file compared to +1 chirality, and they are not in pairs as expected. Could you kindly provide some suggestions or insights on this matter
