### ISSUE TITLE
Did not find right number of bk directions

### ISSUE THREAD

**Issue by YFZHANG101** [quanshengwu/wannier_tools#21]
Hi Sir,

I am trying to do a band calculation, but meet with a problem saying that " Did not find right number of bk directions". Could you please help me with this problem? Thank you in advance!
The following information from wannier90.wout may be helpful:
......
......
......
| 53 0.411434 2 |
| 54 0.411453 2 |
| 55 0.411462 2 |
| 56 0.423182 4 |
| 57 0.423202 4 |
| 58 0.423221 4 |
| 59 0.432500 2 |
| 60 0.432514 2 |
+----------------------------------------------------------------------------+
| The b-vectors are chosen automatically |
| SVD found small singular value, Rejecting this shell and trying the next |
| SVD found small singular value, Rejecting this shell and trying the next |
| SVD found small singular value, Rejecting this shell and trying the next |
| SVD found small singular value, Rejecting this shell and trying the next |
| SVD found small singular value, Rejecting this shell and trying the next |
| SVD found small singular value, Rejecting this shell and trying the next |
| SVD found small singular value, Rejecting this shell and trying the next |
| SVD found small singular value, Rejecting this shell and trying the next |
| SVD found small singular value, Rejecting this shell and trying the next |
| The following shells are used: 1, 2, 3, 16 |
+----------------------------------------------------------------------------+
| Shell # Nearest-Neighbours |
| ----- -------------------- |
| 1 2 |
| 2 2 |
| 3 2 |
| 16 2 |
+----------------------------------------------------------------------------+
| Completeness relation is fully satisfied [Eq. (B1), PRB 56, 12847 (1997)] |
+----------------------------------------------------------------------------+
Exiting.......
Did not find right number of bk directions

**Comment by quanshengwu** [comment]
@YFZHANG101  I am sorry that this is not a question about WannierTools.  I suggest you post this issue to Wannier90 forum in order to get qualified answers.

**Comment by YFZHANG101** [comment]
Thank you all the same.
