### ISSUE TITLE
KPLANE_BULK, SURFACE, KPLANE_SLAB

### ISSUE THREAD

**Issue by alisufyan15** [quanshengwu/wannier_tools#22]
Hi
i am learning wanniertools and the worst thing is that i am also not expert in DFT (actually i switch from particle physics to condensed matter). i have got some idea about waniertools but i have totally failed to understand KPLANE_BULK, SURFACE and KPLANE_SLAB cards. How to define their values? i have read wanniertools documentation but still, i am not able to understand it. can you please describe in simplest way how one can define these cards for different systems? i will be very thankful to you.

**Comment by quanshengwu** [comment]
Please check the new version of online documentation:
http://www.wanniertools.com/input.html#kpathslab

I put some figures to illustrate those three cards. I hope it would help you.
