### ISSUE TITLE
Z2 plot has some abrupt sigularity

### ISSUE THREAD

**Issue by balabi0github** [quanshengwu/wannier_tools#29]
Dear quanshengwu,

Thank you for such a wonderful tool. I am currently studying a 2D material which wannierTools determine it to be a 2D TI.  Here is [one of the Z2 plot](https://pasteboard.co/Hm1hnW3.png) to show topological property that is generated by gnuplot with default setting provided by wanniertools. 

However, I tried to plot the data myself. I found that if I joint each line data, I got [this kind of plot](https://pasteboard.co/Hm1igBq.png). There are obvious abrupt change at k=0 and k=0.11.  

We can see clearly what is going on by overlay data point to line plot and [got this plot](https://pasteboard.co/Hm1jaKq.png) . 

So I am wondering, is it a bug or the material has some problem? Can I safely conclude this material is indeed topological? though the line plot has some singularity.

Looking forward to your reply

best regards!

**Comment by quanshengwu** [comment]
Hi Sir/Madam, 

Welcome to WannierTools. 

I am sorry that you can't use line plot for WCC figures. Instead, you have to use dot plot, especially, when it is nontrivial. 

Best regards, 
Quansheng

**Comment by balabi0github** [comment]
@quanshengwu  Hi, thank you so much for reply. But I am wondering what cause the singularity? What do you mean by nontrivial?
On the other hand, I tried Bi2Se3 in the example folder, and found its line plot is perfect continuous. 
And most importantly, I need a definite answer on whether we can make sure such kind of Z2plot with abnormal line plot is Z2 or not (though I checked surfaceSS, there is indeed gapless surface states)?

best regards!

**Comment by balabi0github** [comment]
@quanshengwu Thank you so much for patient explanation : )
