### ISSUE TITLE
Top and bottom (or left and right) surface bands are different

### ISSUE THREAD

**Issue by Christophergoh** [quanshengwu/wannier_tools#3]
Hi, I used this code to calculate the surface bands of a tetragonal system (a=b=!c) with 48 Wannier projection orbitals from -5 to 7 eV. The wannier fitting looks good, but the surface bands are different for top and bottom (or left and right) surface. Note that it is a non-spin polarized system with SOC. Does anyone has any idea on why they look different? I also notice that the surface bands on the left surface start from the valance states, while the surface bands on the right surface coming from the conduction states.

![surfdos_l](https://cloud.githubusercontent.com/assets/19682675/17073650/7de01370-5027-11e6-9f23-ca4d72001735.png)
![surfdos_r](https://cloud.githubusercontent.com/assets/19682675/17073651/7de4535e-5027-11e6-8e3d-5b73b63200ff.png)

**Comment by quanshengwu** [comment]
Hi, Christophergoh. 
Thanks for the question post.

If you have time reversal symmetry, then the bands at Gamma point should be double degenerate. You can check this with the SlabBand calculation by setting SlabBand_calc= TRUE, and plot the slabek.dat with xmgrace. If it is not double degenerate, then the quality of the Wannier function is not good. It means that the wannier functions of spin up component are different from the spin down component. You should tune the parameters in Wannier90 to get better wannier90_hr.dat.  Please check the wannier spread in wannier90.wout to check the quality of wannier functions.

Another thing should be mentioned  is the Np. Please increase Np from 2 to 4 to check whether the surface state spectrum changes.

**Comment by Christophergoh** [comment]
Thanks. The Np used in the plot above is 8, and I know it is large, just to check for convergence. In fact, Np from 3 to 5 does not change much.

To check for time-reversal symmetry, I am not sure slab band calculation is a good way to check, the TRS happens on the bulk state, so maybe a bulk band calculation is a better way. Nonetheless, I know your slab band calculation put on weights on different states, surface bands are red and bulk bands are yellow. So maybe by looking at the yellow bands we can tell if the TRS is still present.

Here's the slab bands. I can see most bands are degenerate at Gamma. However, it still does not solve the top-bottom-bands-inconsistency problem.

![screenshot](https://cloud.githubusercontent.com/assets/19682675/17266297/62b3bc30-55ab-11e6-9643-b31019af2cd7.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/19682675/17266325/aaf91468-55ab-11e6-8c00-de1525cbd70f.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/19682675/17266326/afaba0ca-55ab-11e6-99ab-deb012105313.png)

**Comment by Christophergoh** [comment]
Hi, we found out that the top and bottom surface bands are different because the system has different terminations, as when we make the slab, we multiply the unit cell by n integer, not n+1/2.

The two surface terminations give two different surface bands, the output files are surfdos_l and surfdos_r, how can you tell which surface bands correspond to which termination?

**Comment by quanshengwu** [comment]
Hi. 
Yes, you are right. The reason for the surface states for top and bottom surface are different is that the terminations are different. You don't have to enlarge the unit cell to get the same surface states. 

You need to check the primitive cell to get the termination. I suggest you to read the iterative green's functions algorithm(J.Phys.F.Met.Phys.15(1985)851-858).
