### ISSUE TITLE
Surface states question

### ISSUE THREAD

**Issue by elementh11** [quanshengwu/wannier_tools#35]
Hello,
In the surface state spectrum plots, ie energy vs high-symmetry k-lines in the 2D BZ, what is the meaning of the coloring? I see in the documentation, at the slab bands calculations section, that there is a surface weights column in the output, but I'm not sure what they mean?
Thank you,
Adrian

**Comment by quanshengwu** [comment]
Usually, we plot log(LDOS(k, E)) in order to highlight the surface contribution. In the default colorscheme, red means more weight on the surface, blue means more weight in the bulk. If you see some negative value in the colorbar, it means you use the log(LDOS(k,E)).

**Comment by elementh11** [comment]
How are the weights assigned to the surface and bulk, respectively?

**Comment by quanshengwu** [comment]
@elementh11 
Sorry about the misleading answer. If you plot the surfdos_l.gnu, the red color means more weight on the surface. However, you could also tell some information from the surfdos_l.png since the surface is connected with the bulk.

**Comment by elementh11** [comment]
In the Fermi arc plot, like the one attached from your examples, what it is represented? What the color scheme represents?
Thank you.

![fermi_arc_wte2](https://user-images.githubusercontent.com/40007158/43656968-561b66a2-9722-11e8-871c-42e1a1bf4b0b.png)

**Comment by quanshengwu** [comment]
@elementh11 

This plot is log(A(k,E0)) vs k.

A(k, E0) is the surface spectrum.
