### ISSUE TITLE
question about surf_onsite

### ISSUE THREAD

**Issue by liuzhsunshine** [quanshengwu/wannier_tools#39]
Dear Dr Wu, 
      To see how the surface state changes, the key word surf_onsite may be used. In my understanding, such a keyword will add additional onsite potential for the dangling electron. But when I use such a term to test my system, I found that such a term doesn't work, even if I set surf_onsite=-100, the surface state is the same to that of surf_onsite=0.  What's wrong?
     
Thank you,
Zhao

**Comment by quanshengwu** [comment]
Dear Dr Zhao, 

If you want to use this term, you have to modify the source code a little bit. 
1.  Please comment "call surfgreen_1985(w,GLL,GRR,GB,H00,H01,ones)" in surfstat.f90 and uncoment "call surfgreen_1984(w,GLL,GRR,GB,H00,H01,ones)". 
2. Do the same thing in fermiarc.f90. 
3.Recompile WannierTools again. 

By the way, the algorithm of version 1985 is faster than that of 1984. 

Best, 
QuanSheng

**Comment by liuzhsunshine** [comment]
Dear Dr Wu,
     Thank you for your kind reply! 

Yours,
Zhao
