### ISSUE TITLE
Some questions about 2D version

### ISSUE THREAD

**Issue by tron1989** [quanshengwu/wannier_tools#4]
Does the new updated 2D version indicated the 2D materials simulated by first principles code such as Vasp? Or is it suitable for the application in 2D materials with first principles which has a large vacumn layer?

When compiling the 2D codes, it seems the subroutine about berry curvature is missing.

**Comment by quanshengwu** [comment]
The 2D version is only works with 2D system, which means it only has two reciprocal lattice vector. At present, it only works with emperical tight binding model written as Wannier90_hr.dat.   

If you construct wannier functions with Wannier90, you should use the 3D version. 

The 2D version is only used to simulate BHZ model, at present. I didn't include all the functions. If you needed the functions. Please list it here. I will try to added them on.

**Comment by tron1989** [comment]
Thanks, I just want to know what your codes can do. By now, I don't need the 2D version of functions.
