### ISSUE TITLE
Mirror Chern number

### ISSUE THREAD

**Issue by Infant83** [quanshengwu/wannier_tools#42]
Is it possible to calculate the mirror Chern number in the current version?

**Comment by quanshengwu** [comment]
Yes, it's possible. 
I uploaded a simple example.
https://github.com/quanshengwu/wannier_tools/tree/master/examples/ZrTe

Please also check with this

http://www.wanniertools.com/features.html#mirrorchernnumbercalculation

**Comment by Infant83** [comment]
Great!
I will consult to your mirror Chern number calculation subroutine.
By the way, what is the biggest obstacle to generalize the Mirror operator?

With regards, 
Hyun-Jung

**Comment by Infant83** [comment]
Hi Quan-Sheng,

I have one question on your "wanniercenter.f90".
When evaluating mirror Chern number, you reconstruct 
hamiltonian hamk as follows :
 M_z * hamk * M_z = mat2
and then, 
hamk = (hamk + mat2)/2

This is your source code for the above process:
           call mat_mul(Num_wann, mirror_z, hamk, mat1)
           call mat_mul(Num_wann, mat1, mirror_z, mat2)
            mat1= (hamk+ mat2)/2.d0
            hamk= mat1

My question is that, why you have insert such procedures (e.g., mat1= (hamk+ mat2)/2.d0) ?

It will be greatly appreciated to get your reply...

Sincerely,
HJ.

**Comment by quanshengwu** [comment]
@Infant83 

This is the final symmetrization of H(k). However, before using this, you need to ensure that the H(k) is symmetric under the mirror symmetry.
