### ISSUE TITLE
2D dispersion calcualtion

### ISSUE THREAD

**Issue by mljphy123** [quanshengwu/wannier_tools#43]
Dear Wu,

Thank you for your WannerTools in advance.
I have a problem when I calculated 2d band dispersion by using Bandbulk_plane_calc = T. I edited all related parameters, such as Nk1,Nk2, KPlane_Bulk, according to the WannierTools_2.2.6_userguide.  But, the 2d dispersion of the example WTe2 (almost all examples in package) maybe wrong because all energy values in the kx-ky plane are constant just like the following picuture:
![image](https://user-images.githubusercontent.com/43056174/45197596-b700ff80-b294-11e8-9465-03dc0d5dbeba.png)

Could you tell me why?Thanks

Best,
Meng

**Comment by quanshengwu** [comment]
@mljphy123 
Dear Meng,

Could you try with the latest version? It could be induced by a bug with 'RCUT" which is not well set up in the old version. 

Best, 
QuanSheng

**Comment by mljphy123** [comment]
Dear QuanSheng,

All calculations are normal for the latest version now . Thank you for your suggestion and your WannierTools.

Best,
Lijun
