### ISSUE TITLE
wannier_tools for 2D system

### ISSUE THREAD

**Issue by lijin18** [quanshengwu/wannier_tools#5]
Mr. Wu, thank you for sharing your codes, which are very useful. You have shown some examples for 3D systems. How to calculate these properties (band structure, Z2, edge states, ...) for 2D system? such as graphene. Thank you.

**Comment by quanshengwu** [comment]
There is a directory called "2d", it is for 2D systems. I will try my best to make it more nicer to users.

**Comment by lijin18** [comment]
That'll be great. Thank you very much!
