### ISSUE TITLE
Chern number calculation

### ISSUE THREAD

**Issue by donsankha** [quanshengwu/wannier_tools#54]
Hi,
    is it possible to calculate chern number for 2D systems using wannier tools? Thanks in advance!

**Comment by quanshengwu** [comment]
@donsankha 
Yes, definitely. 
Just calculate the Chern number at kz=0.

**Comment by donsankha** [comment]
Dear sir,
              thank you very much for the information.

best regards,
Rajdeep

**Comment by Rajdeep621** [comment]
Is it such that D is a node with chirality +1. for a bulk material . in 1d path G-D-G bandstructure there is crossing in D ,  I am expecting berry curvature(z) peak at that point , but instead  I am getting the peak around D in LHS and RHS , my referee is expecting peak at D , and wants to know amplitude
