### ISSUE TITLE
Question for plotting spintexture

### ISSUE THREAD

**Issue by Feng2019001** [quanshengwu/wannier_tools#55]
Hello, i am a new user of WannierTools. For plotting spintexture, i have some confusions about the E_arc parameter in wt.in. 
In WannierTools userguide, the charpter of Spintexture calculation write that Spin texture calculation at fixed energy level E_arc set in NAMELISTS PARAMETERS. 
My question is what means about the fixed energy level. If i want study the spintexture of  VBM and CBM, whether i should set a certain value which lies in VBM or CBM's energy interval.
Thanks for your attention

**Comment by quanshengwu** [comment]
@Feng2019001  

Slabspintext_calc=T calculate the spin texture in a k plane in the BZ at a fixed isoenergy. If you need to calculate the spin texture along some kpaths, then I would need to write another subroutine.
