### ISSUE TITLE
calculation of spin Berry Curvature and Spin Hall conductivity

### ISSUE THREAD

**Issue by nilcm90** [quanshengwu/wannier_tools#56]
Dear QuanSheng,

As I know, currently, Berry Curvature and Anomalous Hall conductivity (AHC) are implemented in the WannierTools package. But I want to calculate spin Berry Curvature and corresponding Spin  Hall conductivity. Is this possible to calculate these two quantity using WannierTools.?  

Thanks

**Comment by quanshengwu** [comment]
@nilcm90 

It's not difficult to implement. However, usually, the spin is not a good quantum number anymore if the spin-orbit coupling is included. So I decide not to implement this part.
