### ISSUE TITLE
About the surfdos_l and surfdos_r

### ISSUE THREAD

**Issue by yanguang21** [quanshengwu/wannier_tools#7]
Dear Mr Wu,
In your wann_tools code, when we calculate the surface states, there are both surfdos_l and surfdos_r be output, sometime the surfdos_l and surfdos_r is different, this because there are different atoms exposed to the left surface and right surface, is it right? If so, how can I judge what atom exposed to the left surface and what aotm exposed on the right surface. Thank you very much.

**Comment by quanshengwu** [comment]
Yes, exactly. Some times the atoms on these two dual surface are different. 

You have to keep in mind that we consider the unit cell as one atom. It means WannierTools don't cut the atoms on the surface exactly the same as experiment.  So you can find the atoms on the outer surface if you  put the unit cell on the lattice you cut.

**Comment by yanguang21** [comment]
Dear Mr Wu,
Thank you for your reply. But I still confused with that how the surface atom corresponds to the surfdos_l or surfdos_r. May be we can discuss it with an example. Let us consider a bcc lattice that A atom located in the center unit cell, where B atom located in  the apex of the unit cell. If we calculate the 010 surface states, then the surfdos_l is corresponded to the surface that A atom termination or B atom termination? On the same time, if we calculate the 001 surface, then the surfdos_l is corresponded to the surface that A atom termination or B termination? thank you!

**Comment by caicaicai123** [comment]
Dear sir,
  I want to know the answer of this question  either. If you already solve this problem, can you tell me ? thank you !

**Comment by high-velocity-rotating-pigeon** [comment]
Dear Mr. Wu
Hello. I am also confused by the definition of left and right surface DOS. Where should I refer to? 
I used to refer to POSCAR_slab for configuration of the edges, but I found when I try to cut an armchair edge of honeycomb lattice, though the two edges are identical, as given by POSCAR_slab, the surface_l and surface_r are still quite different.
