### ISSUE TITLE
OHE tutorial for Cu

### ISSUE THREAD

**Issue by AKB-OU** [quanshengwu/wannier_tools#74]
Dear Dr. QuanSheng Wu,

I am a user of your nice program, WannierTools.

I try to calculate magnetotransport in my material,
and to begin with, I ran the tutorial of Cu included in the "examples" directory with the latest WT (version 2.6.0).

I expected when we set
BTauNum= 5 and      
BTauMax = 40,
the output is an array of Btau [tesla.ps] = {0, 10, 20, 30, 40}.

But my output shows an array of Btau [tesla.ps] = {0.000000E+00, 0.175882E+01, 0.351764E+01, 0.527646E+01, 0.703528E+01}.
All Btau values seem to be multiplied by 0.176.

When I changed the input as
BTauNum= 5 and      
BTauMax = 227.4,
I got the expected Btau values.

I suppose this is a possible bug, or if I misunderstand something, please let me know.

For your reference, I show my input and output for the above calculation.

Best regards,
AKB-OU

wt.in
&TB_FILE
Hrfile = 'wannier90_hr.dat_nsymm48'
/
&CONTROL
Boltz_OHE_calc        = T
Symmetry_Import_calc = T ! please set it to be true for magnetoresistance calculation
/

&SYSTEM
SOC = 0                ! without soc : SOC=0; with soc : SOC=1
E_FERMI = 7.7083       ! e-fermi
Btheta= 0, Bphi= 90    ! magnetic field direction, Btheta is the angle with z axial, Bphi is the angle with respect to x axial in the x-y plane
NumOccupied = 6        ! set it anyway even don't use it.
/

&PARAMETERS
OmegaNum = 1        ! omega number      
OmegaMin =  0.0     ! energy interval
OmegaMax =  0.0     ! energy interval
Nk1 =21            ! Kmesh(1) for KCUBE_BULK
Nk2 =21            ! Kmesh(2) for KCUBE_BULK
Nk3 =21            ! Kmesh(3) for KCUBE_BULK
BTauNum= 5        ! Number of B*tau we calculate
BTauMax = 40      ! The maximum B*tau, starting from Btau=0.
Tmin = 30           ! Temperature in Kelvin
Tmax = 30         ! Temperature in Kelvin
NumT = 1           ! number temperature we calculate. T=Tmin+(Tmax-Tmin)/(NumT-1)
/

LATTICE
Angstrom
   0.0000000   1.8075000   1.8075000
   1.8075000   0.0000000   1.8075000
   1.8075000   1.8075000   0.0000000

ATOM_POSITIONS
1                               ! number of atoms for projectors
Cartisen                          ! Direct or Cartisen coordinate
Cu    0.000000      0.000000      0.000000    

PROJECTORS
9            ! number of projectors
Cu s s s  s s dxy dyz dzx dx2-y2 dz2

SURFACE            ! should be given even don't use
 1  0  0
 0  1  0

SELECTEDBANDS
1
6

KCUBE_BULK
 0.00  0.00  0.00   ! Original point for 3D k plane
 1.00  0.00  0.00   ! The first vector to define 3d k space plane
 0.00  1.00  0.00   ! The second vector to define 3d k space plane
 0.00  0.00  1.00   ! The third vector to define 3d k cube

output (sigma_band6*.dat)
Conductivity tensor \sigma/\tau with unit 1/(Ohm*m*s) for band      6 temperature at          30.0000 K chemical potential at           0.0000 eV
BTau (T.ps)OmegaTau (eV.ps)              xx              xy              xz              yx              yy              yz              zx              zy              zz
    0.000000E+00    0.000000E+00    0.806484E+20    0.401183E+01   -0.108888E+02    0.197491E+02    0.806484E+20   -0.275604E+02   -0.167251E+02    0.575060E+01    0.806484E+20
    0.175882E+01    0.309331E+00    0.828702E+20   -0.972880E+00    0.118171E+01    0.444001E+01    0.828702E+20   -0.450723E+01    0.668697E+01    0.442277E+01    0.828702E+20
    0.351764E+01    0.618663E+00    0.836274E+20   -0.443050E+01   -0.416973E+01    0.206130E+01    0.836274E+20   -0.608853E+01    0.237648E+00    0.502857E+01    0.836274E+20
    0.527646E+01    0.927994E+00    0.833309E+20    0.471297E+01   -0.132255E+01    0.536510E+00    0.833309E+20    0.762548E+00   -0.106279E+01   -0.151829E+01    0.833309E+20
    0.703528E+01    0.123733E+01    0.820936E+20   -0.187407E+01   -0.228758E+01   -0.178246E+01    0.820936E+20    0.226857E+01    0.385121E+01   -0.199164E+01    0.820936E+20

**Comment by quanshengwu** [comment]
@AKB-OU  
Thank you for the report. It could be a bug in the output. Please set BTauMax=40 in the input. I will check the program and update it later.

**Comment by AKB-OU** [comment]
Dr. QuanSheng Wu,

Thank you for the reply.
I look forward to your verification.
