### ISSUE TITLE
How to set the intrinsic magnetic moment of each projected Atom in the ATOM_POSITIONS?

### ISSUE THREAD

**Issue by QuantumInformationGeneral** [quanshengwu/wannier_tools#75]
I am studying the magnetic topological materials.
How could I set the intrinsic magnetic moment of each projected atom for wannier_tools calculation?
From the output file, it seems like I could set the moment tag in the ATOM_POSITIONS. 
However, I could not find any tutorial/explanation.

**Comment by QuantumInformationGeneral** [comment]
Figured it out how to do from the code.

**Comment by hetian-chen** [comment]
@QuantumInformationGeneral May I know how to set magnetic moment?

**Comment by shahid-sattar** [comment]
@QuantumInformationGeneral @hetian-chen have you been able to figure out how to deal with AFM TI in wanniertools? Do we need to specify magnetic moments of Mn atoms in wt.in file?
