### ISSUE TITLE
SURFCARD, Noob basic question 

### ISSUE THREAD

**Issue by GriffithRufo** [quanshengwu/wannier_tools#78]
Hi, I have a question about how to define the surface vectors in terms of vectors R1, R2, and R3.
The R1, R2, and R3 are defined  in WT.out as 
R1= (3, 0, 0) 
R2= (0, 5.92,0)
R3= (0, 0,12) 

I am trying to find the surface spectrum in the kx_ky plane (001). Initially, I m using the following SURFACE _CARD 
SURFACE 
100    !R'1 first vector in surface
010    !R'2  second vector in surface

because I think that the SURFACE_CARD above means

SURFACE 
100    !R'1 = 1.R1 + 0. R2 +0. R3 --> first vector in surface
010    !R'2  = 0 R1 + 1.R2 +0.R3 --> second vector in surface.

Basing on R1, R2 R3, Is my surface card correct?  

thank you so much,
Griffith Rufo.

**Comment by quanshengwu** [comment]
Yes, it's correct. 

Be careful about the space between 1 0 0.

SURFACE
1 0 0 
0 1 0

**Comment by GriffithRufo** [comment]
> Yes, it's correct.
> 
> Be careful about the space between 1 0 0.
> 
> SURFACE
> 1 0 0
> 0 1 0

Dear, quanshengwu thank you so much.  
Best regards.
