### ISSUE TITLE
newer using vasp2wan90 with soc

### ISSUE THREAD

**Issue by ChenqiangHua** [quanshengwu/wannier_tools#8]
Mr Wu, 
    I am juust a newer to learn vasp2wann90.I recently found your tool and wanna have a try by following the examples.But something wrong when using Vasp2wann90 if soc is turned on-- always like Projection   XX done and with nothing going on , comparing to successful running situation without soc.With this problem  i really can't get amn file to have a hr_dat with soc after projection.  I'm confused if vasp interface can support soc with wannier90 when I see your example's using vasp and so many people saying interface is not fully compatible with  wann90 in soc situation .          
   May I have your help to solve my little problem? 
Thanks for your patience.

Chenqiang Hua

**Comment by quanshengwu** [comment]
Hi, Chenqiang, 
which version of wannier90 did you use? 
Till now, VASP is only compatible with wannier90 1.2, while is not compatible with wannier90 2.0.
Please check this.

**Comment by ChenqiangHua** [comment]
Mr.Wu,
  Sir,thanks for your reply. I'm using version 2 so that' the reason.But i have a simple search finding that version 1.2 is not supporting soc(i don' know if it is wrong), and in the example Bi2Se3 the INCAR is written with LSORBIT=T and LWANNIER90=T, using 1.2version can successfully working with soc?

Thanks for your patience.
Chenqiang Hua

**Comment by quanshengwu** [comment]
Hey Chenqiang, 
Yes, Wannier90 1.2 works fine with SOC. Please try it. Please double the num_wanns in wannier90.win comparing to NSOC case

**Comment by ChenqiangHua** [comment]
OK，thanks sir, i will have a try with1.2 version.
Thanks again!
Chenqiang Hua
