### ISSUE TITLE
ISYM question

### ISSUE THREAD

**Issue by dps77** [quanshengwu/wannier_tools#9]
Hello and thanks for nice code!

I saw that in example on Bi2Se3 you used isym=-1 in VASP while preparing for generating Wannier functions. I compared wannier interpolated bulk spectrum for Bi2Se3 with VASP. The first try was without isym=-1. The second was with isym=-1 (full k-mesh). The better correspondence to VASP was in the 2nd case (with isym=-1). Do you know if it is always the case? I am asking because for usual DFT it is managable but I was going to use HSE in future which is much more havy. Can you advise something on this?

Best regards,
Dmitry

**Comment by quanshengwu** [comment]
Dear Dmitry, 

Actually, there are some correspondences. If you use symmetry, then VASP only calculate the wave functions of some of the k points, and then get the rest wave functions through the symmetry operator. Those symmetry operations would cause extra phase discontinuous of wave functions, which is very important for  Wannier functions'   construction. So I suggest you use ISYM = -1 in VASP. 

Best, 
QuanSheng

**Comment by dps77** [comment]
I see, thank you.
